import type { Metadata } from "next";
import "./globals.css";
import ConfigureAmplifyClientSide from "./amplify-cognito-config";
import { inter } from "@/ui/fonts";
import { handleSignOut } from "@/lib/cognitoActions";
import { PowerIcon } from "@heroicons/react/16/solid";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigureAmplifyClientSide />
        {children}
      </body>
    </html>
  );
}
